// Generated by CoffeeScript 1.11.1
(function() {
  var app, express, http, url, user;

  http = require('http');

  user = require('./user');

  url = require('url');

  express = require('express');

  app = express();

  app.set('port', 8086);

  app.set('view engine', 'pug');

  app.set('views', __dirname + "/../views");

  app.get('/', function(req, res) {
    return res.rend('index', {});
  });

  app.get('/hello/:name', function(req, res) {
    return res.send("Hello " + req.params.name);
  });

  app.listen(app.get('port'), function() {
    return console.log("listening on port " + (app.get('port')));
  });

}).call(this);
