// Generated by CoffeeScript 1.11.1
(function() {
  var http, server, user;

  http = require("http");

  user = require('./user');

  server = http.createServer(function(req, res) {
    return user.get('Caroline', function(id) {
      res.writeHead(200, {
        'Content-Type': 'text/plain'
      });
      return res.end('Hello ' + id);
    });
  }).listen(1337);

  console.log("Server is listening.");

}).call(this);
